language: ruby
rvm:
- 2.4.1
cache: bundler
cache:
  directories:
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer

before_install:
  - set -e
  - if [ "${TRAVIS_TAG?}" ]; then
      AWS_BUCKET="www.datacite.org";
      RACK_ENV="production";
      cp .env.master .env;
      AUTO_DEPLOY=true;
    elif [ "$TRAVIS_BRANCH" == "master" ]; then
      AWS_BUCKET="www.stage.datacite.org";
      RACK_ENV="stage";
      CLOUDFRONT_DISTRIBUTION_ID=$CLOUDFRONT_DISTRIBUTION_ID_STAGE;
      cp .env.stage .env;
      AUTO_DEPLOY=true;
    else
      AUTO_DEPLOY=false;
    fi

  - wget https://github.com/jgm/pandoc/releases/download/1.15.2/pandoc-1.15.2-1-amd64.deb
  - sudo dpkg -i pandoc-1.15.2-1-amd64.deb
  - rm pandoc-1.15.2-1-amd64.deb

before_script:
  - cd vendor && npm install
  - cd ../

script:
  - bundle exec middleman build -e $RACK_ENV
  - bundle exec htmlproofer --http-status-ignore "999" --allow-hash-href --only-4xx ./build || true

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $AWS_BUCKET
  local-dir: build
  acl: public_read
  skip_cleanup: true
  region: eu-west-1
  detect_encoding: true
  on:
    condition: $AUTO_DEPLOY = true

after_deploy:
  - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
  - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
  # Allow `awscli` to make requests to CloudFront.
  - aws configure set preview.cloudfront true
  # Invalidate every object in the targeted distribution.
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

notifications:
  slack: datacite:Wt8En0ALoTA6Kjc5EOKNDWxN
  email: false
