# Build settings
markdown: pandoc
highlighter: pygments
gems:
  - jekyll-pandoc
  - jemoji

exclude:
  - README.md
  - LICENCE.md
  - Gemfile
  - Gemfile.lock
  - .travis.yml
  - vendor
  - assets/jquery/*

# Site settings
title: "DataCite Homepage"

defaults:
  - values:
      layout: default

collections:
  about:
    output: true
  members:
    output: true
  services:
    output: true

email: support@datacite.org
logo: "/assets/images/logo.png"
cover: "/assets/images/dc_2.svg"

name: 'DataCite'
author: 'DataCite'
author_image: "/assets/images/author.jpg"

permalink: /:collection/:name:output_ext

url: "http://www.labs.datacite.org" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@datacite'

#fill in disqus shortname to use disqus
#disqus: datacite

#fill in tracking id
google_analytics: UA-22806196-8

# social icons and sharing options
social:
  - icon: twitter
    url:  https://twitter.com/datacite
    desc: Follow DataCite on Twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:  facebook
    url: https://facebook.com/???
    desc: Connect with DataCite on Facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon: github
    url:  https://github.com/datacite
    desc: Visit DataCite on Github
    share_url:
    share_title:
    share_link:

pandoc:
  extensions:
    - normalize
    - smart
    - mathjax
